version: "3"
virtualmachines:
- name: workstation
  image: launchdarkly/workshop-ai-configs
  shell: /bin/bash
  cpus: 4
  memory: 16384
secrets:
- name: AWS_ACCESS_KEY_ID
- name: AWS_SECRET_ACCESS_KEY
- name: AWS_REGION
- name: LAUNCHDARKLY_ACCESS_TOKEN
